name: csv Files to Markdown
description: Process CSV files and convert them to Markdown for documentation.
inputs:
  issue_number:
    description: "The issue number"
    required: true
  github_token:
    description: "GitHub token"
    required: true
runs:
  using: 'composite'
  steps:

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/issue_dataset_to_pr/requirements.txt
        pip install -r scripts/csv_to_markdown/requirements.txt
      shell: bash

    - name: "Run the Python script"
      run: |
        python scripts/issue_dataset_to_pr/main.py 2>error.log
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        PYTHONPATH: ${{ github.workspace }}