name: Issue Dataset to Pull Request

on:
  issues:
    types: [opened]

jobs:
  issue-notification:
    if: |
      contains(github.event.issue.labels.*.name, 'new_dataset') &&
      github.event.issue.state == 'open'
    runs-on: ubuntu-latest

    steps:

    - name: "Issue notification of start of processing"
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: 'Your request is being processed...'
          })

  csv-processing:
    needs: issue-notification
    runs-on: ubuntu-latest

    steps:

    - name: "Clone the repository into the GitHub Actions"
      uses: actions/checkout@v4

    - name: "Create temporary branch"
      run: |
        TEMP_BRANCH="request_new_dataset/branch-issue-${{ github.event.issue.number }}"
        echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV
        git checkout -b $TEMP_BRANCH
        git push --set-upstream origin $TEMP_BRANCH

    - name: "Python script - csv Files to Markdown"
      uses: ./.github/actions/csv_processing
      with:
        issue_number: ${{ github.event.issue.number }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Upload error log if exists"
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: error-log
        path: error.log
    
    - name: "Create Pull Request"
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update data catalog for issue #${{ github.event.issue.number }}"
        committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        branch: ${{ env.TEMP_BRANCH }}
        base: develop
        title: "[NEW DATASET]: Issue #${{ github.event.issue.number }}"
        body: "Automated changes to update the data catalog for issue #${{ github.event.issue.number }}."
        labels: "new_dataset"
  
  csv-error-handling:
    needs: csv-processing
    if: ${{ failure() }}
    runs-on: ubuntu-latest

    steps:
    
    - name: "Download error log artifact"
      uses: actions/download-artifact@v4
      with:
        name: error-log

    - name: "Comment on Issue if Error"
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const errorLog = fs.readFileSync('error.log', 'utf8');
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `An error occurred while processing the issue:\n\n\`\`\`\n${errorLog}\`\`\``
          });
  
  close-issue:
    needs: csv-processing
    runs-on: ubuntu-latest

    steps:

    - name: "Comment & Close the issue"
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: 'Your request has been processed and is awaiting review and approval to be added to the data catalog.'
          })
          github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            state: 'closed'
          })