name: Issue Dataset to Pull Request

on:
  issues:
    types: [opened]

jobs:
  issue-notification:
    if: |
      contains(github.event.issue.labels.*.name, 'new_dataset') &&
      github.event.issue.state == 'open'
    runs-on: ubuntu-latest

    steps:
    - name: "Issue notification of start of processing"
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: 'Your request is being processed...'
          })

  git-preparation:
    needs: issue-notification
    runs-on: ubuntu-latest

    steps:
    - name: "Clone the repository into the GitHub Actions"
      uses: actions/checkout@v4

    - name: "Create temporary branch"
      run: |
        TEMP_BRANCH="request_new_dataset/branch-issue-${{ github.event.issue.number }}"
        echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV
        git checkout -b $TEMP_BRANCH
        git push --set-upstream origin $TEMP_BRANCH

    - name: "Upload repository as artifact"
      uses: actions/upload-artifact@v4
      with:
        name: repo-artifact
        path: |
          .github/workflows/issue_dataset_to_pr
          docs
          scripts

  csv-processing:
    needs: git-preparation
    runs-on: ubuntu-latest

    steps:
    - name: "Download repository as artifact"
      uses: actions/download-artifact@v4
      with:
        name: repo-artifact

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/issue_dataset_to_pr/requirements.txt
        pip install -r scripts/csv_to_markdown/requirements.txt

    - name: "Run the Python script"
      run: |
        python .github/workflows/issue_dataset_to_pr/main.py 2>error.log
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        PYTHONPATH: ${{ github.workspace }}

    - name: "Upload docs as artifact"
      uses: actions/upload-artifact@v4
      with:
        name: data-catalog
        path: docs
    
    - name: "Upload error log if exists"
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: error-log
        path: error.log
    
  csv-error-handling:
    needs: csv-processing
    if: ${{ failure() }}
    runs-on: ubuntu-latest

    steps:
    - name: "Download error log artifact"
      uses: actions/download-artifact@v4
      with:
        name: error-log

    - name: "Comment on Issue if Error"
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const errorLog = fs.readFileSync('error.log', 'utf8');
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `An error occurred while processing the issue:\n\n\`\`\`\n${errorLog}\`\`\``
          });

  git-changes:
    needs: csv-processing
    runs-on: ubuntu-latest

    steps:
    - name: "Download docs artifact"
      uses: actions/download-artifact@v4
      with:
        name: data-catalog

    - name: "Commit and push changes"
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update data catalog for issue #${{ github.event.issue.number }}"
    
    - name: "Create Pull Request"
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: develop
        branch: ${{ env.TEMP_BRANCH }}
        title: "[NEW DATASET]: Issue #${{ github.event.issue.number }}"
        body: "Automated changes to update the data catalog for issue #${{ github.event.issue.number }}."

  close-issue:
    needs: git-changes
    runs-on: ubuntu-latest

    steps:
    - name: "Comment & Close the issue"
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: 'Your request has been processed and is awaiting review and approval to be added to the data catalog.'
          })
          github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            state: 'closed'
          })